// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5Ao48KAW615zSgF3653Rx6ikeLUAm2-k',
    appId: '1:469838232995:web:246ebd1dc1e5fbe547ee16',
    messagingSenderId: '469838232995',
    projectId: 'eps-power-pod',
    authDomain: 'eps-power-pod.firebaseapp.com',
    databaseURL: 'https://eps-power-pod-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'eps-power-pod.firebasestorage.app',
    measurementId: 'G-6GM9KKF5EP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFuxmVxjtggL321CjHh88VWAdP9MZLmvc',
    appId: '1:469838232995:android:e32667f1e5ff1d6647ee16',
    messagingSenderId: '469838232995',
    projectId: 'eps-power-pod',
    databaseURL: 'https://eps-power-pod-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'eps-power-pod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAI6NkcciIHdvRyfp0ljZbVMrK9_TSVrc',
    appId: '1:469838232995:ios:0e74a9649942fd4e47ee16',
    messagingSenderId: '469838232995',
    projectId: 'eps-power-pod',
    databaseURL: 'https://eps-power-pod-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'eps-power-pod.firebasestorage.app',
    iosClientId: '469838232995-9cs5kveentkekl0tkjhjend4e07s2p2s.apps.googleusercontent.com',
    iosBundleId: 'com.example.powerPod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAI6NkcciIHdvRyfp0ljZbVMrK9_TSVrc',
    appId: '1:469838232995:ios:0e74a9649942fd4e47ee16',
    messagingSenderId: '469838232995',
    projectId: 'eps-power-pod',
    databaseURL: 'https://eps-power-pod-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'eps-power-pod.firebasestorage.app',
    iosClientId: '469838232995-9cs5kveentkekl0tkjhjend4e07s2p2s.apps.googleusercontent.com',
    iosBundleId: 'com.example.powerPod',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5Ao48KAW615zSgF3653Rx6ikeLUAm2-k',
    appId: '1:469838232995:web:33215a30fa299ae447ee16',
    messagingSenderId: '469838232995',
    projectId: 'eps-power-pod',
    authDomain: 'eps-power-pod.firebaseapp.com',
    databaseURL: 'https://eps-power-pod-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'eps-power-pod.firebasestorage.app',
    measurementId: 'G-ECDSFMSG7D',
  );

}